### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by mixserrm999** [Abhi0049k/Talkative-Tribe#1]
I can’t to login MongoDB in .env

**Comment by Abhi0049k** [comment]
thank you for letting me know...You can try now

**Comment by mixserrm999** [comment]
yes iit done i chang localhost to 127.0.0.1 but look like show it ![image](https://github.com/Abhi0049k/Group-Chat/assets/61624005/c461f6d6-ce97-4fb1-9632-a78d02a8b2ce)
